# Generated by Django 6.1 on 2026-08-18 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc', models.CharField(max_length=100, unique=True)),
                ('cpu', models.CharField(blank=True, max_length=200)),
                ('ram', models.CharField(blank=True, max_length=50)),
                ('motherboard', models.CharField(blank=True, max_length=200)),
                ('ssd', models.CharField(blank=True, max_length=200)),
                ('gpu', models.CharField(blank=True, max_length=200)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50)),
                ('old_value', models.CharField(blank=True, max_length=200)),
                ('new_value', models.CharField(blank=True, max_length=200)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='inventory.machine')),
            ],
        ),
    ]
