# Generated by Django 6.1 on 2026-08-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='cabinet',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='machine',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
